//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class actionfire
    {
        public long FireID { get; set; }
        public Nullable<System.DateTime> FireDate { get; set; }
        public Nullable<long> eventID { get; set; }
        public Nullable<long> fieldActionID { get; set; }
        public long userMessageID { get; set; }
    }
}
