//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class business
    {
        public int BusinessID { get; set; }
        public byte[] BusinessName { get; set; }
        public byte[] EIN { get; set; }
        public byte[] DocumentLanguage { get; set; }
        public byte[] Address { get; set; }
        public byte[] City { get; set; }
        public byte[] Zip { get; set; }
        public byte[] Phone { get; set; }
        public byte[] Fax { get; set; }
        public byte[] Country { get; set; }
        public byte[] State { get; set; }
        public Nullable<long> isDeleted { get; set; }
    }
}
