//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class calendars
    {
        public long calendarID { get; set; }
        public string usersID { get; set; }
        public byte[] googleusername { get; set; }
        public byte[] googlepsw { get; set; }
        public byte[] googlecalendar { get; set; }
        public byte[] calendarName { get; set; }
        public string GroupsID { get; set; }
        public long IsDeleted { get; set; }
        public Nullable<long> AccessKind { get; set; }
        public string LastCalendarsList { get; set; }
        public Nullable<System.TimeSpan> ActiveTimeFrom { get; set; }
        public Nullable<System.TimeSpan> ActiveTimeTo { get; set; }
        public Nullable<long> OnlyActiveTime { get; set; }
        public Nullable<long> DisplayUnits { get; set; }
    }
}
