//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cati_fields
    {
        public long cati_fieldID { get; set; }
        public Nullable<byte> cati { get; set; }
        public byte[] title { get; set; }
        public byte[] FieldName { get; set; }
        public Nullable<long> isRequired { get; set; }
        public Nullable<long> CustomFieldID { get; set; }
        public Nullable<long> CFieldID { get; set; }
    }
}
