//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cati_fields_action
    {
        public long cati_actionID { get; set; }
        public Nullable<long> cati { get; set; }
        public Nullable<long> cati_fieldID { get; set; }
        public Nullable<long> cati_BoxID { get; set; }
        public Nullable<long> NextFormID { get; set; }
        public Nullable<long> StatusID { get; set; }
    }
}
