//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cati
    {
        public long CatiID { get; set; }
        public Nullable<long> CampaignID { get; set; }
        public Nullable<long> isFirst { get; set; }
        public byte[] Body { get; set; }
        public byte[] FormName { get; set; }
        public Nullable<long> NextCatiID { get; set; }
    }
}
