//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class currency
    {
        public int CurrencyID { get; set; }
        public byte[] Currency1 { get; set; }
        public byte[] Symbol { get; set; }
        public decimal ExchangeRate { get; set; }
        public byte[] CurrencyCode { get; set; }
        public Nullable<int> LocaleID { get; set; }
        public Nullable<long> deleted { get; set; }
        public long isDefault { get; set; }
        public byte[] Country { get; set; }
    }
}
