//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class customfields_box
    {
        public long BoxID { get; set; }
        public Nullable<long> FieldID { get; set; }
        public byte[] Value { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<long> ParentRecord { get; set; }
        public byte[] ValueKey { get; set; }
    }
}
