//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class customfields_action
    {
        public long actionID { get; set; }
        public Nullable<long> FieldID { get; set; }
        public Nullable<long> FieldType { get; set; }
        public Nullable<System.DateTime> NextFireDate { get; set; }
        public System.DateTime LastFireDate { get; set; }
    }
}
