//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class customtable68
    {
        public long RecordID { get; set; }
        public Nullable<long> ParentRecordID { get; set; }
        public Nullable<long> EntityId { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<long> OrderID { get; set; }
    }
}
