//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class customlistbox
    {
        public int listID { get; set; }
        public Nullable<long> groupID { get; set; }
        public byte[] value { get; set; }
        public Nullable<long> imageIndex { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<long> userID { get; set; }
        public Nullable<long> isDeleted { get; set; }
        public Nullable<long> color { get; set; }
        public byte[] ListPermitionGroups { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    }
}
