//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class customfields
    {
        public long FieldID { get; set; }
        public byte[] FieldName { get; set; }
        public Nullable<long> Type { get; set; }
        public Nullable<long> Required { get; set; }
        public Nullable<long> userID { get; set; }
        public Nullable<long> FormID { get; set; }
        public Nullable<long> Width { get; set; }
        public Nullable<int> ALeft { get; set; }
        public Nullable<long> Height { get; set; }
        public Nullable<long> Top { get; set; }
        public Nullable<long> TabOrder { get; set; }
        public long plateID { get; set; }
        public Nullable<System.DateTime> NextFireDate { get; set; }
        public System.DateTime LastFireDate { get; set; }
        public long IntervalEvery { get; set; }
        public Nullable<long> FaxMessageID { get; set; }
        public Nullable<long> EmailMessageID { get; set; }
        public Nullable<byte> SMSMessageID { get; set; }
        public Nullable<long> TelemarketingID { get; set; }
        public Nullable<long> StationID { get; set; }
        public Nullable<long> isFocused { get; set; }
        public Nullable<System.DateTime> StationTimeOut { get; set; }
        public Nullable<long> ParentFieldID { get; set; }
        public byte[] Formula { get; set; }
        public Nullable<long> ShowInGrid { get; set; }
        public Nullable<long> ShowCaption { get; set; }
        public Nullable<long> DependentFieldID { get; set; }
        public Nullable<long> ContainsKeyData { get; set; }
        public Nullable<long> Max { get; set; }
        public Nullable<long> Min { get; set; }
        public Nullable<long> MaxDelta { get; set; }
        public Nullable<long> ColumnWidth { get; set; }
        public Nullable<long> autoinc { get; set; }
        public Nullable<long> isphone { get; set; }
        public Nullable<long> TodayDate { get; set; }
        public byte[] DefaultValue { get; set; }
        public Nullable<long> IsIndexed { get; set; }
    }
}
