//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class entities
    {
        public long entityID { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public byte[] FirstName { get; set; }
        public byte[] LastName { get; set; }
        public byte[] Company { get; set; }
        public byte[] Address { get; set; }
        public byte[] City { get; set; }
        public byte[] State { get; set; }
        public byte[] Country { get; set; }
        public byte[] Zip { get; set; }
        public byte[] Phone { get; set; }
        public Nullable<long> AllowPhone { get; set; }
        public byte[] Mobile { get; set; }
        public Nullable<long> AllowMobile { get; set; }
        public byte[] Fax { get; set; }
        public Nullable<long> AllowFax { get; set; }
        public byte[] Email { get; set; }
        public Nullable<long> AllowEmail { get; set; }
        public byte[] isChecked { get; set; }
        public Nullable<long> CryptedID { get; set; }
        public byte[] SharedUsers { get; set; }
        public Nullable<long> isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<long> DeletedBy { get; set; }
        public Nullable<long> MergedID { get; set; }
        public Nullable<int> CustomField3 { get; set; }
        public string CustomField9 { get; set; }
        public byte[] CustomField10 { get; set; }
        public byte[] CustomField14 { get; set; }
        public byte[] CustomField15 { get; set; }
        public byte[] CustomField16 { get; set; }
        public byte[] CustomField17 { get; set; }
        public Nullable<long> CustomField18 { get; set; }
        public byte[] CustomField19 { get; set; }
        public Nullable<long> CustomField20 { get; set; }
        public Nullable<long> CustomField21 { get; set; }
        public Nullable<System.DateTime> CustomAction6 { get; set; }
        public byte[] CustomField23 { get; set; }
        public byte[] CustomField24 { get; set; }
        public byte[] CustomField25 { get; set; }
        public Nullable<long> CustomField39 { get; set; }
        public byte[] CustomField51 { get; set; }
        public Nullable<int> CustomField52 { get; set; }
        public Nullable<long> CustomField53 { get; set; }
        public byte[] CustomField60 { get; set; }
        public Nullable<System.DateTime> CustomField61 { get; set; }
        public byte[] CustomField62 { get; set; }
        public Nullable<System.DateTime> CustomField64 { get; set; }
        public Nullable<long> CustomField65 { get; set; }
        public byte[] CustomField67 { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<long> isSupplier { get; set; }
        public Nullable<long> isUser { get; set; }
        public Nullable<long> isCustomer { get; set; }
    }
}
