//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class entities_files
    {
        public long FileID { get; set; }
        public long entityID { get; set; }
        public byte[] Filename { get; set; }
        public Nullable<long> Width { get; set; }
        public Nullable<long> ALeft { get; set; }
        public Nullable<long> Height { get; set; }
        public Nullable<long> Top { get; set; }
        public byte[] Label { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public byte[] filedata { get; set; }
        public Nullable<int> DataSize { get; set; }
        public byte[] Type { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
