//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class entities_events
    {
        public int eventID { get; set; }
        public Nullable<int> entityID { get; set; }
        public Nullable<long> userID { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<System.DateTime> ScheduledDate { get; set; }
        public Nullable<System.TimeSpan> DurationTime { get; set; }
        public Nullable<long> Remind { get; set; }
        public long LocationID { get; set; }
        public long EventType { get; set; }
        public byte[] Remark { get; set; }
        public Nullable<long> userID2 { get; set; }
        public Nullable<long> PhoneConfirmed { get; set; }
        public Nullable<long> Success { get; set; }
        public Nullable<long> isPrivetEvent { get; set; }
        public Nullable<System.DateTime> EventDateEnd { get; set; }
        public Nullable<int> statusID { get; set; }
        public Nullable<System.DateTime> EvenReminderDate { get; set; }
        public byte[] Body { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public Nullable<long> calendarID { get; set; }
        public string googleeventID { get; set; }
        public Nullable<System.DateTime> LastSyncDate { get; set; }
        public Nullable<long> CustomField51 { get; set; }
    }
}
