//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class incoming
    {
        public long IncomingID { get; set; }
        public Nullable<long> IncomingKind { get; set; }
        public Nullable<long> IncomingState { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> AcceptedDate { get; set; }
        public Nullable<System.DateTime> DisconnectedDate { get; set; }
        public Nullable<long> StationID { get; set; }
        public Nullable<long> entityID { get; set; }
        public Nullable<long> userID { get; set; }
        public Nullable<long> isDeleted { get; set; }
        public byte[] IncomingTo { get; set; }
        public byte[] IncomingFrom { get; set; }
        public byte[] IncomingFromName { get; set; }
        public Nullable<long> deviceID { get; set; }
        public Nullable<long> StatusID { get; set; }
        public byte[] Remarks { get; set; }
        public Nullable<long> ReSpoolID { get; set; }
        public byte[] Body { get; set; }
    }
}
