//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class messages
    {
        public long MessageID { get; set; }
        public Nullable<long> UserID { get; set; }
        public string Body { get; set; }
        public Nullable<long> Type { get; set; }
        public byte[] MessageName { get; set; }
        public long SavedAsCampaign { get; set; }
        public Nullable<long> Status { get; set; }
        public byte[] Title { get; set; }
        public Nullable<long> Device { get; set; }
        public Nullable<long> ContentType { get; set; }
        public byte[] Subject { get; set; }
        public string Attachments { get; set; }
        public Nullable<long> Priority { get; set; }
        public byte[] Images { get; set; }
        public Nullable<long> DocumentType { get; set; }
        public byte[] Language { get; set; }
        public Nullable<long> Deleted { get; set; }
        public byte[] CurrencyCode { get; set; }
        public Nullable<long> isEMF { get; set; }
        public Nullable<long> version { get; set; }
        public Nullable<System.DateTime> LastModifyDate { get; set; }
        public Nullable<long> BusinessID { get; set; }
        public byte[] MailCC { get; set; }
        public byte[] MailBCC { get; set; }
        public byte[] PermissionGroups { get; set; }
        public byte[] AttachmentFiles { get; set; }
        public byte[] GroupsID { get; set; }
        public Nullable<long> Orientation { get; set; }
    }
}
