//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders_products_purchase
    {
        public int order_purchase_productsID { get; set; }
        public Nullable<int> order_productID { get; set; }
        public Nullable<int> purchase_productID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> InventoryID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
