//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders_payment
    {
        public long order_paymentID { get; set; }
        public long PaymentID { get; set; }
        public long PaymentType { get; set; }
        public byte[] PaymentName { get; set; }
        public Nullable<decimal> PaymentValue { get; set; }
        public Nullable<decimal> PaymentTotal { get; set; }
        public byte[] Identification { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public byte[] PayerName { get; set; }
        public byte[] PayerNumber { get; set; }
        public byte[] PayerNumber2 { get; set; }
        public byte[] PayerNumber3 { get; set; }
        public byte[] PayerNumber4 { get; set; }
        public byte[] PayerNumber5 { get; set; }
        public Nullable<System.DateTime> PayerDate { get; set; }
        public byte[] Parm1 { get; set; }
        public Nullable<long> currencyID { get; set; }
        public Nullable<long> status { get; set; }
        public long PaymentGroup { get; set; }
        public Nullable<long> orderID { get; set; }
        public long entityID { get; set; }
        public Nullable<long> ReciptID { get; set; }
        public Nullable<long> isDeleted { get; set; }
        public Nullable<long> CancelReciptID { get; set; }
        public Nullable<long> BusinessID { get; set; }
        public Nullable<System.DateTime> ChargedDate { get; set; }
        public Nullable<int> PaymentQty { get; set; }
        public Nullable<long> RecurringNumber { get; set; }
        public Nullable<long> RetryCharge { get; set; }
        public Nullable<System.DateTime> NextChargeRetryDate { get; set; }
        public Nullable<long> RetryChargeQuantity { get; set; }
        public Nullable<long> approved { get; set; }
        public byte[] DeclinedRemark { get; set; }
        public byte[] ChargedRemark { get; set; }
        public Nullable<System.DateTime> SendToCCDate { get; set; }
        public byte[] PaymentNeto { get; set; }
        public Nullable<long> isForRecurring { get; set; }
        public Nullable<System.DateTime> DeclinedDate { get; set; }
    }
}
