//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders_products
    {
        public long productID { get; set; }
        public Nullable<long> ParentID { get; set; }
        public Nullable<long> StockID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public byte[] productName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PriceVat { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<long> currencyID { get; set; }
        public Nullable<long> isDeleted { get; set; }
        public Nullable<decimal> TotalVat { get; set; }
        public Nullable<long> InventoryID { get; set; }
        public long InvoiceID { get; set; }
        public Nullable<long> RefundID { get; set; }
        public Nullable<long> PriceWithVAT { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<long> ShippingLabelID { get; set; }
        public Nullable<long> ReturnLabelID { get; set; }
        public Nullable<long> entityID { get; set; }
        public Nullable<long> BusinessID { get; set; }
        public Nullable<long> RecurringNumber { get; set; }
        public Nullable<long> isRecurrence { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<decimal> PaymentAmountTotal { get; set; }
        public Nullable<int> AllowPriceChange { get; set; }
        public byte[] CustomField33 { get; set; }
        public string CustomField40 { get; set; }
        public byte[] CustomField111 { get; set; }
        public Nullable<long> CustomField112 { get; set; }
        public Nullable<System.DateTime> CustomField113 { get; set; }
        public Nullable<System.DateTime> CustomField114 { get; set; }
        public Nullable<long> CustomField116 { get; set; }
        public byte[] CustomField1 { get; set; }
        public Nullable<System.DateTime> CustomField2 { get; set; }
        public Nullable<long> CustomField46 { get; set; }
        public Nullable<long> CustomField47 { get; set; }
        public string CustomField63 { get; set; }
        public byte[] CustomField9 { get; set; }
        public string CustomField66 { get; set; }
        public Nullable<int> AffiliateKind { get; set; }
        public Nullable<decimal> AffiliateValue { get; set; }
        public Nullable<long> isForRecurring { get; set; }
        public Nullable<System.DateTime> OrderProductDate { get; set; }
    }
}
