//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public long OrderID { get; set; }
        public Nullable<long> Status { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public long entityID { get; set; }
        public long userID { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> TotalPaid { get; set; }
        public Nullable<long> InvoiceID { get; set; }
        public Nullable<long> ReceiptID { get; set; }
        public Nullable<long> Deleted { get; set; }
        public Nullable<long> currencyID { get; set; }
        public Nullable<decimal> TotalVAT { get; set; }
        public byte[] Merged_ordersID { get; set; }
        public decimal Tax { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<long> CreatedByUserID { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> DiscountPCT { get; set; }
        public Nullable<long> DiscountType { get; set; }
        public Nullable<double> OrderExchangeRate { get; set; }
        public Nullable<long> Recurrence { get; set; }
        public Nullable<long> Charge_payments { get; set; }
        public Nullable<long> Generate_Invoice { get; set; }
        public Nullable<long> SendInvoiceByFax { get; set; }
        public Nullable<long> SendInvoiceByEmail { get; set; }
        public Nullable<long> PrintInvoice { get; set; }
        public Nullable<long> Bills_every { get; set; }
        public Nullable<long> Bills_every_period { get; set; }
        public Nullable<long> Billing_for { get; set; }
        public Nullable<long> Billing_for_period { get; set; }
        public Nullable<long> RecurringParentOrderID { get; set; }
        public Nullable<long> RecurringNumber { get; set; }
        public Nullable<System.DateTime> Deleted_Date { get; set; }
        public Nullable<long> Deleted_ByUserID { get; set; }
        public Nullable<int> RecurringTotal { get; set; }
        public Nullable<System.DateTime> Next_Bill_Date { get; set; }
        public Nullable<System.DateTime> OrderPaymentDate { get; set; }
        public Nullable<long> AgentID { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<long> BusinessID { get; set; }
        public Nullable<int> RecurringStatus { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<System.DateTime> Last_Bill_Date { get; set; }
        public Nullable<System.DateTime> Closed_Date { get; set; }
        public Nullable<long> Generate_Recipt { get; set; }
        public Nullable<System.DateTime> RecurringActiveDate { get; set; }
        public Nullable<System.DateTime> RecurringStatusChangedDate { get; set; }
        public Nullable<int> RecurringEventID { get; set; }
        public Nullable<long> LockedBy { get; set; }
        public Nullable<System.DateTime> LockedDate { get; set; }
        public int StopIfPaymentFailed { get; set; }
    }
}
