//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders_events
    {
        public int orders_eventID { get; set; }
        public Nullable<int> RecurringStatus { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> ServiceUserID { get; set; }
        public Nullable<int> SMSMessageID { get; set; }
        public Nullable<int> Next_eventID { get; set; }
        public Nullable<int> StartAfterDays { get; set; }
    }
}
