//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class outgoing
    {
        public int OutgoingID { get; set; }
        public Nullable<int> MessageID { get; set; }
        public Nullable<int> EntityID { get; set; }
        public byte[] Destination { get; set; }
        public Nullable<int> Status { get; set; }
        public byte[] AttachmentFiles { get; set; }
        public Nullable<int> Priority { get; set; }
        public byte[] Images { get; set; }
        public Nullable<int> isEMF { get; set; }
        public Nullable<System.DateTime> LastModifyDate { get; set; }
        public Nullable<int> Orientation { get; set; }
        public Nullable<int> StationID { get; set; }
        public Nullable<System.DateTime> StationTimeOut { get; set; }
        public Nullable<System.DateTime> ScheduleTo { get; set; }
        public Nullable<int> ScheduleByUserID { get; set; }
        public byte[] Device { get; set; }
        public Nullable<int> ErrorCode { get; set; }
        public byte[] ErrorMessage { get; set; }
        public Nullable<int> Copies { get; set; }
        public byte[] Log { get; set; }
        public Nullable<int> Retries { get; set; }
        public Nullable<int> MessageType { get; set; }
        public Nullable<int> SentByUserID { get; set; }
        public byte[] Source { get; set; }
    }
}
