//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class payments
    {
        public long paymentID { get; set; }
        public byte[] PaymentName { get; set; }
        public long PaymentType { get; set; }
        public byte[] Icon { get; set; }
        public long Postion { get; set; }
        public long userID { get; set; }
        public long deleted { get; set; }
        public byte[] Component { get; set; }
        public Nullable<int> currencyID { get; set; }
        public Nullable<System.DateTime> LastDateUsed { get; set; }
    }
}
