//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class permissionsgroup
    {
        public long PermissionGroupID { get; set; }
        public byte[] GroupName { get; set; }
        public byte[] permissions { get; set; }
        public string ReadOnlyFields { get; set; }
        public string HiddenFields { get; set; }
        public string CannotAddRowFields { get; set; }
        public string CannotRemoveRowFields { get; set; }
        public byte[] AllowPlugins { get; set; }
        public byte[] CustomFieldPlates { get; set; }
    }
}
