//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public long ProductID { get; set; }
        public long CategoryID { get; set; }
        public long stockID { get; set; }
        public long OwnerProductID { get; set; }
        public byte[] ProductName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<long> Recurring { get; set; }
        public Nullable<long> ParentProductID { get; set; }
        public Nullable<decimal> PriceVAT { get; set; }
        public Nullable<int> IncludesVAT { get; set; }
        public Nullable<long> currencyID { get; set; }
        public Nullable<long> isDeleted { get; set; }
        public byte[] SerialNumber { get; set; }
        public Nullable<long> ParentID { get; set; }
        public byte[] Barcode { get; set; }
        public long userID { get; set; }
        public Nullable<long> isRecurrence { get; set; }
        public Nullable<long> Bills_every { get; set; }
        public Nullable<long> Bills_every_period { get; set; }
        public Nullable<long> Billing_for { get; set; }
        public Nullable<long> Billing_for_period { get; set; }
        public Nullable<long> Charge_payments { get; set; }
        public Nullable<long> Generate_Invoice { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<int> AllowPriceChange { get; set; }
        public Nullable<long> Generate_Recipt { get; set; }
        public string CustomField66 { get; set; }
        public Nullable<int> AffiliateKind { get; set; }
        public Nullable<decimal> AffiliateValue { get; set; }
        public byte[] smallimage { get; set; }
        public byte[] largeimage { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Depth { get; set; }
        public Nullable<decimal> AgentBonus { get; set; }
        public Nullable<int> BonusType { get; set; }
        public Nullable<int> BonusRecurring { get; set; }
        public Nullable<int> MinAlertLevel { get; set; }
        public Nullable<int> AssignServiceTo { get; set; }
        public string Description { get; set; }
    }
}
