//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_stock
    {
        public int stockID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<long> userID { get; set; }
        public byte[] Serial { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<System.DateTime> inDate { get; set; }
        public Nullable<System.DateTime> outDate { get; set; }
        public Nullable<long> status { get; set; }
    }
}
