//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_rent
    {
        public long rentID { get; set; }
        public Nullable<long> entityID { get; set; }
        public Nullable<long> RentedByUserID { get; set; }
        public Nullable<long> AcceptedByUserID { get; set; }
        public Nullable<System.DateTime> RentedDate { get; set; }
        public Nullable<System.DateTime> RentedUntil { get; set; }
        public Nullable<System.DateTime> ReturnedDate { get; set; }
        public Nullable<long> isDeleted { get; set; }
        public string RentRemarks { get; set; }
        public string ReturnRemarks { get; set; }
        public Nullable<long> ReturnStatusID { get; set; }
        public Nullable<long> productID { get; set; }
    }
}
