//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_payment
    {
        public long purchase_paymentID { get; set; }
        public Nullable<long> BusinessID { get; set; }
        public long PaymentID { get; set; }
        public long PaymentType { get; set; }
        public byte[] PaymentName { get; set; }
        public Nullable<decimal> PaymentValue { get; set; }
        public byte[] Identification { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<System.DateTime> ChargedDate { get; set; }
        public Nullable<long> currencyID { get; set; }
        public Nullable<long> status { get; set; }
        public Nullable<long> purchaseID { get; set; }
        public long entityID { get; set; }
        public Nullable<decimal> PaymentTotal { get; set; }
        public Nullable<long> isDeleted { get; set; }
        public Nullable<long> approved { get; set; }
        public byte[] ChargedRemark { get; set; }
        public byte[] PayerName { get; set; }
        public byte[] PayerNumber { get; set; }
        public byte[] PayerNumber2 { get; set; }
        public byte[] PayerNumber3 { get; set; }
        public byte[] PayerNumber4 { get; set; }
        public byte[] PayerNumber5 { get; set; }
        public Nullable<System.DateTime> PayerDate { get; set; }
        public byte[] Parm1 { get; set; }
        public Nullable<int> ReciptID { get; set; }
        public Nullable<int> CancelReciptID { get; set; }
        public Nullable<int> RetryCharge { get; set; }
        public Nullable<int> RetryChargeQuantity { get; set; }
    }
}
