//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase
    {
        public long purchaseID { get; set; }
        public Nullable<long> businessID { get; set; }
        public Nullable<long> status { get; set; }
        public Nullable<System.DateTime> purchaseDate { get; set; }
        public Nullable<System.DateTime> deliveryDate { get; set; }
        public Nullable<System.DateTime> arrivedDate { get; set; }
        public Nullable<System.DateTime> lastUpdate { get; set; }
        public long entityID { get; set; }
        public long userID { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> totalPaid { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<long> deleted { get; set; }
        public Nullable<System.DateTime> deleted_Date { get; set; }
        public Nullable<long> deleted_ByUserID { get; set; }
        public Nullable<long> currencyID { get; set; }
        public Nullable<decimal> totalVAT { get; set; }
        public decimal tax { get; set; }
        public Nullable<long> createdByUserID { get; set; }
        public Nullable<double> orderExchangeRate { get; set; }
    }
}
