//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_task
    {
        public long taskID { get; set; }
        public Nullable<long> TaskGroupID { get; set; }
        public Nullable<long> serviceID { get; set; }
        public Nullable<long> EntityID { get; set; }
        public byte[] task { get; set; }
        public byte[] solution { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<long> CreatedByUserID { get; set; }
        public Nullable<long> AssignedTo { get; set; }
        public Nullable<long> AssignedBy { get; set; }
        public Nullable<long> PriorityID { get; set; }
        public Nullable<long> StatusID { get; set; }
        public Nullable<int> AllowCloseFlags { get; set; }
        public Nullable<int> AllowCloseID { get; set; }
        public byte[] reason { get; set; }
        public Nullable<System.DateTime> DeadLine { get; set; }
        public Nullable<long> Reassigned { get; set; }
        public Nullable<long> ReassignedId { get; set; }
        public Nullable<System.DateTime> Reminder { get; set; }
        public Nullable<long> ReminderON { get; set; }
        public Nullable<long> Parent { get; set; }
        public byte[] Reassignments { get; set; }
        public Nullable<long> Addtextflag { get; set; }
        public Nullable<long> AccessKind { get; set; }
        public Nullable<int> UsedByUserID { get; set; }
        public Nullable<System.DateTime> Timeout { get; set; }
    }
}
