//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class spooler
    {
        public long spoolID { get; set; }
        public Nullable<long> messageID { get; set; }
        public long messageType { get; set; }
        public Nullable<long> EntityID { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> StationID { get; set; }
        public Nullable<System.DateTime> StationTimeOut { get; set; }
        public Nullable<System.DateTime> spoolDate { get; set; }
        public Nullable<System.DateTime> changedDate { get; set; }
        public System.DateTime ScheduleTo { get; set; }
        public long ScheduleByUserID { get; set; }
        public int Priority { get; set; }
        public Nullable<int> Device { get; set; }
        public Nullable<long> ErrorCode { get; set; }
        public byte[] ErrorMessage { get; set; }
        public Nullable<long> Copies { get; set; }
        public string Log { get; set; }
        public Nullable<long> Visible { get; set; }
        public Nullable<int> Orientation { get; set; }
        public Nullable<long> userID { get; set; }
        public int Order_DocumentID { get; set; }
        public Nullable<long> Retries { get; set; }
        public byte[] color { get; set; }
        public Nullable<long> AutoDialHangUp { get; set; }
        public Nullable<long> TotalTalkTime { get; set; }
    }
}
