//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class system_parameters
    {
        public long ParmID { get; set; }
        public byte[] ParmName { get; set; }
        public byte[] ParmValue { get; set; }
        public byte[] ParmValue2 { get; set; }
        public byte[] ParmValue3 { get; set; }
        public byte[] ParmValue4 { get; set; }
        public byte[] ParmValue5 { get; set; }
        public byte[] ParmValue6 { get; set; }
        public byte[] ParmValue7 { get; set; }
        public byte[] ParmValue8 { get; set; }
        public byte[] ParmValue9 { get; set; }
        public byte[] ParmValue10 { get; set; }
        public byte[] ParmValue11 { get; set; }
        public byte[] ParmValue12 { get; set; }
        public byte[] ParmValue13 { get; set; }
        public byte[] ParmValue14 { get; set; }
        public byte[] ParmValue15 { get; set; }
        public byte[] ParmValue16 { get; set; }
        public byte[] ParmValue17 { get; set; }
        public byte[] ParmValue18 { get; set; }
        public byte[] ParmValue19 { get; set; }
        public byte[] ParmValue20 { get; set; }
    }
}
