//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class systemlog
    {
        public long LogID { get; set; }
        public byte[] LogAction { get; set; }
        public Nullable<long> userID { get; set; }
        public byte[] userName { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
    }
}
