//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class telemarketing_shift
    {
        public int ShiftID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> FirstCallDate { get; set; }
        public Nullable<System.DateTime> LastCallDate { get; set; }
    }
}
