//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class telemarketing_phone_script
    {
        public long scriptID { get; set; }
        public long CampaignID { get; set; }
        public byte[] Title { get; set; }
        public string Body { get; set; }
        public Nullable<long> stationID { get; set; }
        public Nullable<long> Postion { get; set; }
        public byte[] WaveFile { get; set; }
    }
}
