//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class telemarketing_status
    {
        public long statusID { get; set; }
        public byte[] caption { get; set; }
        public Nullable<long> isRemarkRequired { get; set; }
        public Nullable<long> isSendFax { get; set; }
        public Nullable<long> isSendEmail { get; set; }
        public Nullable<long> isSendSMS { get; set; }
        public Nullable<long> RedialType { get; set; }
        public Nullable<System.TimeSpan> RedialDailyTime { get; set; }
        public Nullable<int> isRestoreCallToGlobal { get; set; }
        public Nullable<long> FaxMessageID { get; set; }
        public Nullable<long> EmailMessageID { get; set; }
        public Nullable<long> SMSMessageID { get; set; }
        public Nullable<long> TelemarketingID { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public byte[] color { get; set; }
        public Nullable<long> isDialNextEntity { get; set; }
        public Nullable<long> SystemStatusID { get; set; }
        public Nullable<long> ChangeStatusRetries { get; set; }
        public Nullable<long> ChangeStatusID { get; set; }
        public Nullable<long> CampaignType { get; set; }
        public Nullable<System.DateTime> LastUsed { get; set; }
        public Nullable<long> Priority { get; set; }
        public Nullable<long> TelemarketingDeleteFromCurrent { get; set; }
        public Nullable<int> CaptionID { get; set; }
    }
}
