//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class telemarketing_history
    {
        public long HistoryID { get; set; }
        public Nullable<long> spoolID { get; set; }
        public long CampaignID { get; set; }
        public long entityID { get; set; }
        public long userID { get; set; }
        public Nullable<long> StatusID { get; set; }
        public byte[] StatusCaption { get; set; }
        public byte[] Remark { get; set; }
        public System.DateTime CallStarted { get; set; }
        public Nullable<System.DateTime> CallAnswered { get; set; }
        public System.DateTime CallEnded { get; set; }
        public System.DateTime ScheduleTo { get; set; }
        public Nullable<long> CampaignType { get; set; }
        public byte[] PhoneNumber { get; set; }
        public byte[] CampaignName { get; set; }
        public byte[] username { get; set; }
        public Nullable<long> StationID { get; set; }
        public Nullable<long> DialCount { get; set; }
    }
}
