//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class telemarketing
    {
        public long CampaignID { get; set; }
        public byte[] CampaignName { get; set; }
        public Nullable<long> FaxMessageID { get; set; }
        public Nullable<long> EmailMessageID { get; set; }
        public Nullable<long> SMSMessageID { get; set; }
        public string UsersID { get; set; }
        public Nullable<long> CampaignType { get; set; }
        public long deleted { get; set; }
        public Nullable<long> HideCampaignHistory { get; set; }
        public long AutoDialNextCampaign { get; set; }
        public long RescheduledCallByOperator { get; set; }
        public Nullable<long> AutoOpenEntity { get; set; }
        public Nullable<long> BusinessID { get; set; }
        public int ActiveSpooler { get; set; }
        public int FinishedSpooler { get; set; }
        public byte[] DisabledStatuss { get; set; }
        public Nullable<long> isCustomPhone { get; set; }
        public Nullable<long> isCustomPhoneCategoryID { get; set; }
        public int ScheduledSpooler { get; set; }
        public long ScheduledCallOwnFor { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<int> AccessKind { get; set; }
        public byte[] GroupsID { get; set; }
        public int RequestStatusAfterEachCall { get; set; }
        public int StatusIDAfterEachCall { get; set; }
        public long IsMaxRescheduledDays { get; set; }
        public long MaxRescheduledDays { get; set; }
        public long StatusIDMaxRescheduled { get; set; }
        public long SysStatusIDMaxRescheduled { get; set; }
        public byte[] ScriptFileName { get; set; }
        public Nullable<int> AutoDialerLineQty { get; set; }
        public Nullable<long> AutoDialerNoAnswerAfter { get; set; }
    }
}
