//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class textdata
    {
        public int tdID { get; set; }
        public byte[] Enu { get; set; }
        public byte[] Rus { get; set; }
        public byte[] Ukr { get; set; }
        public byte[] Heb { get; set; }
    }
}
