//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tickets
    {
        public long TicketID { get; set; }
        public Nullable<long> EntityID { get; set; }
        public Nullable<long> TicketStatus { get; set; }
        public Nullable<long> CreatedByUserID { get; set; }
        public Nullable<long> AssignedToUserID { get; set; }
        public Nullable<long> ModifiedByUserID { get; set; }
        public Nullable<System.DateTime> TicketDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> StatusID { get; set; }
        public Nullable<long> Priority { get; set; }
        public byte[] Subject { get; set; }
        public byte[] Description { get; set; }
        public byte[] Resolution { get; set; }
    }
}
