//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_messager
    {
        public int messageID { get; set; }
        public Nullable<long> to_userID { get; set; }
        public Nullable<long> from_userID { get; set; }
        public Nullable<System.DateTime> send_on_date { get; set; }
        public Nullable<System.DateTime> sent_date { get; set; }
        public Nullable<System.DateTime> received_date { get; set; }
        public string body { get; set; }
        public long isread { get; set; }
    }
}
