//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_payroll
    {
        public int payrollID { get; set; }
        public Nullable<System.DateTime> payrollDate { get; set; }
        public int userID { get; set; }
        public int WorkingDays { get; set; }
        public Nullable<int> WorkingTime { get; set; }
        public Nullable<decimal> Vacation { get; set; }
        public Nullable<decimal> Sick { get; set; }
        public Nullable<decimal> TravelPay { get; set; }
        public Nullable<decimal> PerHour { get; set; }
        public Nullable<decimal> Bonuses { get; set; }
        public Nullable<decimal> TotalForHours { get; set; }
        public Nullable<decimal> TotalPay { get; set; }
    }
}
