//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_group
    {
        public long User_GroupID { get; set; }
        public byte[] GroupName { get; set; }
        public Nullable<long> ViewAllInbox { get; set; }
        public Nullable<long> isDeleted { get; set; }
        public byte[] DisallowUsersTap { get; set; }
    }
}
