//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MekashronTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_visible_fields
    {
        public long visible_fieldsID { get; set; }
        public Nullable<long> UserID { get; set; }
        public byte[] title { get; set; }
        public byte[] name { get; set; }
        public Nullable<long> width { get; set; }
        public Nullable<long> ColumnIndex { get; set; }
        public byte[] OrderBy { get; set; }
        public byte[] bgColor { get; set; }
    }
}
